# Generated by Django 4.2.29 on 2026-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_eventi_formazioni_progetti_soci_delete_socio_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('partnership', models.TextField(blank=True, db_column='Partnership', null=True)),
                ('tipologia', models.TextField(blank=True, db_column='Tipologia', null=True)),
                ('oggetto_primario', models.TextField(blank=True, db_column='Oggetto primario della partnership', null=True)),
                ('status_partnership', models.TextField(blank=True, db_column='Status partnership', null=True)),
                ('data_firma', models.TextField(blank=True, db_column='Data firma', null=True)),
                ('anno', models.FloatField(blank=True, db_column='ANNO', null=True)),
                ('durata', models.TextField(blank=True, db_column='Durata', null=True)),
                ('rinnovo', models.TextField(blank=True, db_column='Rinnovo', null=True)),
                ('data_ultimo_rinnovo', models.TextField(blank=True, db_column='Data ultimo rinnovo', null=True)),
                ('data_fine_prevista', models.TextField(blank=True, db_column='Data fine prevista', null=True)),
                ('numero_progetti', models.TextField(blank=True, db_column='Numero di progetti prodotti dalle Partnership', null=True)),
                ('numero_partecipanti', models.TextField(blank=True, db_column='Numero di partecipanti', null=True)),
                ('contatti', models.TextField(blank=True, db_column='Contatti', null=True)),
                ('cartella_sul_drive', models.TextField(blank=True, db_column='Cartella sul drive', null=True)),
                ('vantaggi_partner', models.TextField(blank=True, db_column='Vantaggi partner', null=True)),
                ('compenso_economico', models.TextField(blank=True, db_column='Compenso economico', null=True)),
                ('url_cartella_drive', models.TextField(blank=True, db_column='Url cartella drive', null=True)),
            ],
            options={
                'db_table': 'PARTNERSHIP',
                'managed': False,
            },
        ),
    ]
