# Generated by Django 6.0.3 on 2026-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_partnership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipNonFin',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('realta', models.TextField(blank=True, db_column='Realtà', null=True)),
                ('contatti', models.TextField(blank=True, db_column='Contatti', null=True)),
                ('periodo', models.TextField(blank=True, db_column='Periodo', null=True)),
                ('anno', models.FloatField(blank=True, db_column='Anno', null=True)),
                ('cartella', models.TextField(blank=True, db_column='Cartella', null=True)),
            ],
            options={
                'db_table': 'PARTNERSHIP_NON_FIN',
                'managed': False,
            },
        ),
    ]
