# Generated by Django 4.2.29 on 2026-09-27 15:09

from django.db import migrations, models

# Supabase espone `public` via PostgREST alla chiave anon: RLS senza policy
# blocca anon/authenticated. Django (ruolo postgres) e service_role hanno
# BYPASSRLS → nessun impatto sull'app.
RLS_TABLES = ("TASKS", "TASKS_ASSEGNATARI", "CREDENZIALI")


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY')


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE public."{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("lead_id", models.TextField(primary_key=True, serialize=False)),
                ("data_creazione", models.DateField(blank=True, null=True)),
                ("data_primo_contatto", models.DateField(blank=True, null=True)),
                ("azienda", models.TextField()),
                ("titolare_azienda", models.TextField(blank=True, null=True)),
                ("referente", models.TextField(blank=True, null=True)),
                ("nome_referente", models.TextField(blank=True, null=True)),
                ("cognome_referente", models.TextField(blank=True, null=True)),
                ("email_referente", models.TextField(blank=True, null=True)),
                ("telefono", models.TextField(blank=True, null=True)),
                ("prodotto_servizio", models.TextField(blank=True, null=True)),
                ("area", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                ("fase_attuale", models.TextField(default="Nuovo")),
                ("stato_lead", models.TextField(default="Attiva")),
                (
                    "stato_contratto",
                    models.TextField(blank=True, default="Da preparare", null=True),
                ),
                ("priorita", models.TextField(blank=True, null=True)),
                (
                    "valore_stimato",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("probabilita", models.SmallIntegerField(blank=True, null=True)),
                (
                    "valore_ponderato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("prossima_azione", models.TextField(blank=True, null=True)),
                ("data_prossima_azione", models.DateField(blank=True, null=True)),
                (
                    "alert_follow_up",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                ("drive_folder_id", models.TextField(blank=True, null=True)),
                ("link_cartella_drive", models.TextField(blank=True, null=True)),
                ("cartella_fase_drive", models.TextField(blank=True, null=True)),
                (
                    "storico_aggiornamenti",
                    models.JSONField(blank=True, default=list, editable=False),
                ),
                (
                    "ultimo_aggiornamento",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "db_table": "LEADS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Credenziale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Generale", "Generale"),
                            ("D&A", "D&A"),
                            ("BD", "BD"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                        ],
                        max_length=16,
                    ),
                ),
                ("servizio", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password_cifrata", models.TextField(blank=True, editable=False)),
                ("note_cifrate", models.TextField(blank=True, editable=False)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("modificato_da", models.CharField(blank=True, max_length=255)),
                ("modificato_il", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "credenziali",
                "db_table": "CREDENZIALI",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("D&A", "D&A"),
                            ("BD", "BD"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "competenza",
                    models.CharField(
                        blank=True,
                        help_text="Sottogruppo/i dell'area, separati da virgola (es. Data, Automations).",
                        max_length=255,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("Da iniziare", "Da iniziare"),
                            ("In corso", "In corso"),
                            ("Completata", "Completata"),
                        ],
                        default="Da iniziare",
                        max_length=32,
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alta", "Alta"),
                            ("Media", "Media"),
                            ("Bassa", "Bassa"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scadenza", models.DateField(blank=True, null=True)),
                ("descrizione", models.TextField(blank=True)),
                ("link", models.TextField(blank=True, help_text="Un link per riga.")),
                ("altri_assegnatari", models.TextField(blank=True)),
                ("creato_da", models.CharField(blank=True, max_length=255)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("modificato_da", models.CharField(blank=True, max_length=255)),
                ("modificato_il", models.DateTimeField(auto_now=True)),
                (
                    "assegnatari",
                    models.ManyToManyField(
                        blank=True,
                        db_constraint=False,
                        db_table="TASKS_ASSEGNATARI",
                        related_name="tasks",
                        to="dashboard.soci",
                    ),
                ),
            ],
            options={
                "db_table": "TASKS",
            },
        ),
        migrations.DeleteModel(
            name="PartnershipNonFin",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
