# Generated by Django 4.2.29 on 2026-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.TextField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateField(blank=True, null=True)),
                ('data_primo_contatto', models.DateField(blank=True, null=True)),
                ('azienda', models.TextField()),
                ('titolare_azienda', models.TextField(blank=True, null=True)),
                ('referente', models.TextField(blank=True, null=True)),
                ('nome_referente', models.TextField(blank=True, null=True)),
                ('cognome_referente', models.TextField(blank=True, null=True)),
                ('email_referente', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('prodotto_servizio', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('fase_attuale', models.TextField(default='Nuovo')),
                ('stato_lead', models.TextField(default='Attiva')),
                ('stato_contratto', models.TextField(blank=True, default='Da preparare', null=True)),
                ('priorita', models.TextField(blank=True, null=True)),
                ('valore_stimato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('probabilita', models.SmallIntegerField(blank=True, null=True)),
                ('valore_ponderato', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('prossima_azione', models.TextField(blank=True, null=True)),
                ('data_prossima_azione', models.DateField(blank=True, null=True)),
                ('alert_follow_up', models.BooleanField(blank=True, editable=False, null=True)),
                ('drive_folder_id', models.TextField(blank=True, null=True)),
                ('link_cartella_drive', models.TextField(blank=True, null=True)),
                ('cartella_fase_drive', models.TextField(blank=True, null=True)),
                ('storico_aggiornamenti', models.JSONField(blank=True, default=list, editable=False)),
                ('ultimo_aggiornamento', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'LEADS',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PartnershipNonFin',
        ),
    ]
