# Generated by Django 4.2.29 on 2026-09-27 16:02

from django.db import migrations, models
import django.db.models.deletion

# RLS senza policy: blocca anon/authenticated su PostgREST (dati personali dei
# candidati). Django (postgres) e service_role hanno BYPASSRLS.
RLS_TABLES = ("REC_SESSIONI", "REC_GRUPPI", "REC_CANDIDATI", "REC_COLLOQUI", "REC_EMAIL")


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY')


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE public."{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_task_credenziali"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_candidatura", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("nome", models.CharField(max_length=100)),
                ("cognome", models.CharField(max_length=100)),
                ("data_nascita", models.CharField(blank=True, max_length=30)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("ateneo", models.CharField(blank=True, max_length=255)),
                ("facolta", models.CharField(blank=True, max_length=255)),
                ("corso_laurea", models.CharField(blank=True, max_length=255)),
                ("anno_frequenza", models.CharField(blank=True, max_length=100)),
                ("residenza", models.CharField(blank=True, max_length=255)),
                ("cv_url", models.CharField(blank=True, max_length=500)),
                (
                    "area_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BD", "BD"),
                            ("D&A", "D&A"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                            ("Legal", "Legal"),
                            ("IT", "IT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "area_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BD", "BD"),
                            ("D&A", "D&A"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                            ("Legal", "Legal"),
                            ("IT", "IT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("fonte", models.CharField(blank=True, max_length=255)),
                ("motivazione", models.TextField(blank=True)),
                ("conosce_jesap", models.CharField(blank=True, max_length=255)),
                ("conosce_je_italy", models.CharField(blank=True, max_length=255)),
                ("altre_risposte", models.JSONField(blank=True, default=dict)),
                (
                    "esito_screening",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Passato", "Passato"),
                            ("Scartato", "Scartato"),
                            ("Doppione", "Doppione"),
                        ],
                        max_length=16,
                    ),
                ),
                ("presenza_gruppo", models.BooleanField(blank=True, null=True)),
                ("link_output", models.CharField(blank=True, max_length=500)),
                (
                    "punteggio_output",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("link_scheda_gruppo", models.CharField(blank=True, max_length=500)),
                (
                    "punteggio_soft_gruppo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "esito_gruppo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ammesso", "Ammesso"),
                            ("Non ammesso", "Non ammesso"),
                            ("Indeciso", "Indeciso"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "area_prova",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BD", "BD"),
                            ("D&A", "D&A"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                            ("Legal", "Legal"),
                            ("IT", "IT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("conferma_area", models.BooleanField(default=False)),
                ("mail_jesap_creata", models.BooleanField(default=False)),
                ("form_compilato", models.BooleanField(default=False)),
                ("gruppo_telegram", models.BooleanField(default=False)),
                (
                    "esito_finale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ammesso", "Ammesso"),
                            ("Non ammesso", "Non ammesso"),
                            ("Prolungato", "Prolungato"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "settimane_prolungamento",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("modificato_il", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "REC_CANDIDATI",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSessione",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Es. Fall REC 25", max_length=100, unique=True
                    ),
                ),
                (
                    "aperta",
                    models.BooleanField(
                        default=False,
                        help_text="Le nuove candidature dal form finiscono in questa sessione (una sola aperta alla volta).",
                    ),
                ),
                (
                    "conferma_automatica",
                    models.BooleanField(
                        default=True,
                        help_text="Invia subito l'email di conferma ricezione a ogni nuova candidatura.",
                    ),
                ),
                ("link_welcome_day", models.CharField(blank=True, max_length=500)),
                ("template_email", models.JSONField(blank=True, default=dict)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "REC_SESSIONI",
                "ordering": ["-creato_il"],
            },
        ),
        migrations.CreateModel(
            name="GruppoColloquio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("data", models.DateField(blank=True, null=True)),
                ("ora", models.TimeField(blank=True, null=True)),
                (
                    "luogo",
                    models.CharField(
                        blank=True, help_text="Aula o link Meet", max_length=255
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "recruiter_1",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.soci",
                    ),
                ),
                (
                    "recruiter_2",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.soci",
                    ),
                ),
                (
                    "recruiter_3",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.soci",
                    ),
                ),
                (
                    "sessione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gruppi",
                        to="dashboard.recruitmentsessione",
                    ),
                ),
            ],
            options={
                "db_table": "REC_GRUPPI",
            },
        ),
        migrations.CreateModel(
            name="EmailCandidato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=32)),
                ("destinatario", models.EmailField(max_length=254)),
                ("oggetto", models.CharField(max_length=255)),
                ("corpo", models.TextField()),
                ("inviata_il", models.DateTimeField(auto_now_add=True)),
                ("inviata_da", models.CharField(blank=True, max_length=255)),
                ("ok", models.BooleanField(default=False)),
                ("errore", models.TextField(blank=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_log",
                        to="dashboard.candidato",
                    ),
                ),
            ],
            options={
                "db_table": "REC_EMAIL",
                "ordering": ["-inviata_il"],
            },
        ),
        migrations.CreateModel(
            name="ColloquioIndividuale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Prima scelta", "Prima scelta"),
                            ("Seconda scelta", "Seconda scelta"),
                        ],
                        default="Prima scelta",
                        max_length=16,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BD", "BD"),
                            ("D&A", "D&A"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                            ("Legal", "Legal"),
                            ("IT", "IT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("con_resp_vice", models.BooleanField(default=False)),
                ("presenza_confermata", models.BooleanField(default=False)),
                ("link_meet", models.CharField(blank=True, max_length=500)),
                ("data", models.DateField(blank=True, null=True)),
                ("ora", models.TimeField(blank=True, null=True)),
                ("presenza", models.BooleanField(blank=True, null=True)),
                (
                    "durata_minuti",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "punteggio_soft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "punteggio_hard",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("link_scheda", models.CharField(blank=True, max_length=500)),
                (
                    "esito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ammesso", "Ammesso"),
                            ("Non ammesso", "Non ammesso"),
                            ("Seconda scelta", "Seconda scelta"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "area_probabile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BD", "BD"),
                            ("D&A", "D&A"),
                            ("HR", "HR"),
                            ("M&C", "M&C"),
                            ("Legal", "Legal"),
                            ("IT", "IT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colloqui",
                        to="dashboard.candidato",
                    ),
                ),
                (
                    "recruiter_hr",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.soci",
                    ),
                ),
                (
                    "recruiter_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.soci",
                    ),
                ),
            ],
            options={
                "db_table": "REC_COLLOQUI",
            },
        ),
        migrations.AddField(
            model_name="candidato",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidati",
                to="dashboard.gruppocolloquio",
            ),
        ),
        migrations.AddField(
            model_name="candidato",
            name="sessione",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidati",
                to="dashboard.recruitmentsessione",
            ),
        ),
        migrations.AddConstraint(
            model_name="gruppocolloquio",
            constraint=models.UniqueConstraint(
                fields=("sessione", "numero"), name="rec_gruppo_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="colloquioindividuale",
            constraint=models.UniqueConstraint(
                fields=("candidato", "tipo"), name="rec_colloquio_tipo_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="candidato",
            index=models.Index(
                fields=["sessione", "email"], name="rec_cand_sessione_email"
            ),
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
